Add argument of GitHub base API endpoint config
cloudposse/terraform-github-repository-webhooks pull request #14
Opened 2020-03-19 06:37 UTC by uchiumih

Add support for GitHub Enterprise.

2020-04-17 02:19 UTC, maximmi requested changes
@uchiumih please, rebase the PR

2020-05-12 13:07 UTC, maximmi commented
/codefresh run test

2020-06-10 21:27 UTC, osterman commented
/test all

2020-06-10 23:11 UTC, osterman commented
Closed in #18 

Thanks for pointing this out! We had some tests that needed fixing so I took care of it there.

2020-06-10 23:11 UTC, closed without merging