feat: allow anonymous access if token not set
cloudposse/terraform-github-repository-webhooks pull request #15
Opened 2020-04-08 17:22 UTC by jhosteny

If this module is used in the [code pipeline module](https://github.com/cloudposse/terraform-aws-ecs-codepipeline) (e.g., in the [ECS web app module](https://github.com/cloudposse/terraform-aws-ecs-web-app)), the provider fails with bad credentials, even if the pipeline or webhooks are disabled.

By setting anonymous access on the provider configuration when the token is not provided, this problem is avoided.

A longer term fix is probably (as others have suggested) to remove the code pipeline from the web app module.

2020-04-17 02:17 UTC, maximmi requested changes
@jhosteny please, rebase the PR

2020-04-18 01:03 UTC, maximmi commented
/codefresh run test

2020-04-18 01:17 UTC, maximmi approved these changes
thanks @jhosteny

2020-04-18 01:17 UTC, merged

2020-04-22 12:37 UTC, jhosteny commented
Hi @maximmi, can you push a new tag with this change at some point? I'd like to thread it back up all the way into https://github.com/cloudposse/terraform-aws-ecs-web-app.

2020-04-22 20:33 UTC, maximmi commented
@jhosteny here is new release: https://github.com/cloudposse/terraform-github-repository-webhooks/releases/tag/0.6.0